### ISSUE TITLE
Restructure FAQ - discussion

### ISSUE THREAD

**Issue by MaudSimon** [alephium/docs#110]
@Sakrecoer I'm thinking that we could improve the readability of the FAQ by having the different questions categories as sub-pages of the FAQ instead of having everything in one big pages. 
What do you think ?

**Comment by Sakrecoer** [comment]
I like this idea very much! Would keep it sane (as opposed to bloated) while reatining it somewhat central (as opposed to having a separate FAQ in each category of the wiki)
