### ISSUE TITLE
Host at docs.alephium.org 

### ISSUE THREAD

**Issue by mvaivre** [alephium/docs#115]
Following a discussion on Slack, it seems that hosting our "wiki" (ie. documentation) at docs.alephium.org would make more sense. 

Let's create an alias and a redirect from wiki.alephium.org to docs.alephium.org?

cc/ @killerwhile @polarker

**Comment by killerwhile** [comment]
Here you are --> https://docs.alephium.org/
there are currently no redirections, i.e. both URL are serving the files. This gives us a bit of time to fine tune, and then I'll start sending "permanent redirect" from the wiki URL so that search engines will updates their indexes.

**Comment by mvaivre** [comment]
That's awesome! Thanks a lot!
