### ISSUE TITLE
Migrate all content before publishing to production

### ISSUE THREAD

**Issue by nop33** [alephium/docs#12]
I noticed a few differences between the new and old wikis:
- [x] 1. New wiki does not include [changes in Full Node More page](https://github.com/alephium/wiki/pull/50)
- [x] 2. New wiki does not include [FAQ page](https://github.com/alephium/wiki/blob/master/src/Frequently-Asked-Questions.md)
- [x] 3. There's a [desktop wallet page PR](https://github.com/alephium/wiki/pull/46) on the old wiki, which needs to be moved in the new wiki, before Wednesday
- [x] 4. There's [another PR](https://github.com/alephium/wiki/pull/49) open whose changes probably need to be reflected in the new wiki as well
- [x] 5. In the new wiki, the order of the articles in each section is not the same as in the old one

@Sakrecoer I'll take care of points 1 and 3

**Comment by nop33** [comment]
I am taking care of 5 as well.

**Comment by Sakrecoer** [comment]
Thank you @nop33, i'll fix the other points!

**Comment by Sakrecoer** [comment]
regarding 4. you saw this right, @nop33 ?
https://github.com/alephium/new-wiki/pull/10

**Comment by nop33** [comment]
yes, that's why I chcked it ✅  thanks!
