### ISSUE TITLE
301 redirects

### ISSUE THREAD

**Issue by Sakrecoer** [alephium/docs#18]
We need to redirect the endpoints of the old wiki to the new wiki.

Here CSV file with this pattern `oldURL,newURL`

:warning: note that line 15 contains a `#`deeplink wich might cause trouble depending on how the list is parsed: 
`https://wiki.alephium.org/Roadmap.html, https://wiki.alephium.org/5min-overview#roadmap`

If this doesnt work, please use `https://wiki.alephium.org/Roadmap.html, https://wiki.alephium.org/5min-overview`

```
https://wiki.alephium.org/Introduction.html,https://wiki.alephium.org/
https://wiki.alephium.org/Frequently-Asked-Questions.html,https://wiki.alephium.org/frequently-asked-questions
https://wiki.alephium.org/Full-Node-Starter-Guide.html,https://wiki.alephium.org/full-node/Full-Node-Starter-Guide
https://wiki.alephium.org/Docker-Guide.html,https://wiki.alephium.org/full-node/Docker-Guide
https://wiki.alephium.org/Full-Node-More.html,https://wiki.alephium.org/full-node/Full-Node-More
https://wiki.alephium.org/Full-node-on-raspberry-pi.html,https://wiki.alephium.org/full-node/Full-node-on-raspberry-pi
https://wiki.alephium.org/Solo-Mining-Guide.html,https://wiki.alephium.org/mining/Solo-Mining-Guide
https://wiki.alephium.org/Pool-Mining-Guide.html,https://wiki.alephium.org/mining/Pool-Mining-Guide
https://wiki.alephium.org/Miner-Troubleshooting.html,https://wiki.alephium.org/mining/Miner-Troubleshooting
https://wiki.alephium.org/Alephium-Stratum.html,https://wiki.alephium.org/mining/Alephium-Stratum
https://wiki.alephium.org/Wallet-Guide.html,https://wiki.alephium.org/wallet/Wallet-Guide
https://wiki.alephium.org/Multisig-Guide.html,https://wiki.alephium.org/wallet/Multisig-Guide
https://wiki.alephium.org/Smart-Contract-Guide.html,https://wiki.alephium.org/smart-contract/Smart-Contract-Guide
https://wiki.alephium.org/Smart-Contract-More.html,https://wiki.alephium.org/smart-contract/Smart-Contract-More
https://wiki.alephium.org/Roadmap.html,https://wiki.alephium.org/5min-overview#roadmap
https://wiki.alephium.org/Testnet-Guide.html,https://wiki.alephium.org/testnet-and-devnet/Testnet-Guide
https://wiki.alephium.org/Devnet-Guide.html,https://wiki.alephium.org/testnet-and-devnet/Devnet-Guide
https://wiki.alephium.org/CPU-Miner-Guide.html,https://wiki.alephium.org/testnet-and-devnet/CPU-Miner-Guide
https://wiki.alephium.org/On-dust-outputs-and-state-explosion.html,https://wiki.alephium.org/misc/On-dust-outputs-and-state-explosion
https://wiki.alephium.org/Internationalization-and-Localization.html,https://wiki.alephium.org/misc/Internationalization-and-Localization

```

**Comment by nop33** [comment]
@killerwhile would it be easy to add these redirects on the server side? If not, it's ok, I can do it on the client side.

**Comment by nop33** [comment]
> https://wiki.alephium.org/Wallet-Guide.html,https://wiki.alephium.org/wallet/Desktop-Wallet-Guide

This is wrong, it should be:
```
https://wiki.alephium.org/Wallet-Guide.html,https://wiki.alephium.org/wallet/Wallet-Guide
```

**Comment by polarker** [comment]
Since we will deprecate the old links one day, shall we just deprecate them right now?

**Comment by nop33** [comment]
I think we should just have permanent redirects to offer the best UX.

**Comment by Sakrecoer** [comment]
yes, 301 is [permanent redirection code.](https://en.wikipedia.org/wiki/HTTP_301)

regarding the error. There was only one page about the wallet on the old wiki (according to the list you gave me @nop33 )

I chose to put the wallet desktop there, because it's the easiest.

**Comment by Sakrecoer** [comment]
@nop33 how did you go about with this in the end? There is currently a redirect happening, but i'm not sure how to leverage it. We could need a little restructuring as per #29 and i assume it is worth redirecting those pages properly as well.

**Comment by nop33** [comment]
https://github.com/alephium/wiki/blob/master/docusaurus.config.js#L136-L209

**Comment by Sakrecoer** [comment]
closing this as has been sorted out
