### ISSUE TITLE
Template provided code having issues under "Test" command

### ISSUE THREAD

**Issue by larkben** [alephium/docs#186]
benjaminlarkey@pop-os:~/Desktop/ContractsAlph/alephium-tutorial$ npx @alephium/cli@latest test
 FAIL  test/token.test.ts
  ● Test suite failed to run

    test/token.test.ts:125:32 - error TS2339: Property 'contractId' does not exist on type 'DeployContractExecutionResult<ContractInstance>'.

    125       const tokenId = deployed.contractId
                                       ~~~~~~~~~~
    test/token.test.ts:126:37 - error TS2339: Property 'contractAddress' does not exist on type 'DeployContractExecutionResult<ContractInstance>'.

    126       const tokenAddress = deployed.contractAddress
                                            ~~~~~~~~~~~~~~~
    test/token.test.ts:127:23 - error TS2339: Property 'groupIndex' does not exist on type 'DeployContractExecutionResult<ContractInstance>'.

    127       expect(deployed.groupIndex).toEqual(testGroup)
                              ~~~~~~~~~~

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.961 s
Ran all test suites.
node:child_process:960
    throw err;
    ^

Error: Command failed: npx --yes ts-node --transpile-only /home/benjaminlarkey/Desktop/ContractsAlph/alephium-tutorial/node_modules/@alephium/cli/cli_internal.ts test
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Object.<anonymous> (/home/benjaminlarkey/Desktop/ContractsAlph/alephium-tutorial/node_modules/@alephium/cli/cli.js:34:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 52311,
  stdout: null,
  stderr: null
}

Node.js v19.9.0

**Comment by polarker** [comment]
Hey @larkben, thanks for reporting ❤️  It's fixed in `0.10.3` which will be released in minutes.

**Comment by larkben** [comment]
No problem, I really want to be able to learn how to build dapps and contracts on Alephium; I think this will help those new and those transitioning.

**Comment by polarker** [comment]
> No problem, I really want to be able to learn how to build dapps and contracts on Alephium; I think this will help those new and those transitioning.

It should be not too hard given your programming background. Don't hesitate to ask questions on Discord, cheer!
