### ISSUE TITLE
Remove (French) Translation for now

### ISSUE THREAD

**Issue by MaudSimon** [alephium/docs#209]
After discussing with @nop33  to understand how translations are managed by Docusaurus, I would like to suggest that we remove the French translation for now (it is very outdated) and until the documentation is more stable. 

For reminder this is how it works:

> To create a translation for a new page, one needs to copy the English file into the i18n/fr/docusaurus-plugin-content-docs/current/ folder and update the text to the new language.
> If no-one  create a translation for a page, when the user switches to the new language, they will see the English content instead.
> Because it works at the page level and not the actual content level, once both English and new language files are created, and there is some new text added in the English one, there’s no way to know that the 2 files are not in sync anymore.

The only way to ensure proper maintenance of the translated pages would be that once someone changes something in the English files and makes a PR, we don’t merge that PR until we also have the other translations for it. 
As we are currently working a lot on the documentation, I don't think this is a bottleneck we can manage right now. It's also a bit of a waste of community time to make them translate content that evolves so quickly.

It would be more efficient to wait until the documentation is more stable to accept translation, and then, we can enforce that EN PR modifying a page, need to have all translated languages updated as well. 

Wdyt? @mvaivre @VDAODAO @polarker ?

**Comment by polarker** [comment]
I am not that much involved in French translation, so I guess you guys know it better.

**Comment by nop33** [comment]
Just for the record, I'll mention Crowdin here as well: https://translate.alephium.org/
