### ISSUE TITLE
testnet snapshot not found (404)

### ISSUE THREAD

**Issue by ferdinandhodl** [alephium/docs#276]
this might be a bug or just an inconvenience:
testnet snapshot [https://archives.alephium.org/archives/testnet/full-node-data/_latest.txt](https://archives.alephium.org/archives/testnet/full-node-data/_latest.txt) returns a 404
while
mainnet snapshot [https://archives.alephium.org/archives/mainnet/full-node-data/_latest.txt](https://archives.alephium.org/archives/mainnet/full-node-data/_latest.txt) works fine

would be useful to have a snapshot of the testnet db available too

source: [docs/full-node/loading-snapshot.md](https://github.com/alephium/docs/blob/78975bfb0e0371d1291e7a828ee2d1ed0691025d/docs/full-node/loading-snapshot.md?plain=1#L29)

**Comment by polarker** [comment]
@ferdinandhodl Thanks. We will get it back the infra devs have the bandwidth.

**Comment by ferdinandhodl** [comment]
Thank you @polarker 🙏🏻
additionally you might want to add a checksum file for the snapshots, containing shasum for the respective files

**Comment by polarker** [comment]
> Thank you @polarker 🙏🏻 additionally you might want to add a checksum file for the snapshots, containing shasum for the respective files

Yes, checksum is already there, but in a separate file: https://archives.alephium.org/archives/mainnet/full-node-data/_latest.txt.sha256sum

**Comment by ferdinandhodl** [comment]
looks like [testnet snapshot](https://archives.alephium.org/archives/testnet/full-node-data/_latest.txt) and [checksum](https://archives.alephium.org/archives/testnet/full-node-data/_latest.txt.sha256sum) are there now. - Thank you infra team! 🙏🏻
