### ISSUE TITLE
Amend the list of community driven Telegram channels

### ISSUE THREAD

**Issue by Sakrecoer** [alephium/docs#32]
As contributed by @ferdinandhodl in https://github.com/alephium/www/issues/71

- [x] Edit Overview page to link to internationalization page instead of listing the language specific channels

**Comment by Sakrecoer** [comment]
@ferdinandhodl you submitted a Discord link in the original issue, but the link appears to be broken. (https://discord.gg/z4UYxksZ) Would you care for getting a new one, or indicating which discord server it is pointing to? Thank you :)

**Comment by Sakrecoer** [comment]
Forgot we have this page: https://wiki.alephium.org/misc/Internationalization-and-Localization

I will add a link to that section in the Overview as to not have to update both places.

**Comment by ferdinandhodl** [comment]
> @ferdinandhodl you submitted a Discord link in the original issue, but the link appears to be broken. (https://discord.gg/z4UYxksZ) Would you care for getting a new one, or indicating which discord server it is pointing to? Thank you :)

I updated the links to the discord community channels on alephium/www/issues/71 as requested

**Comment by Sakrecoer** [comment]
Awesome! Thank you for elaborating! Since new users need to verify themselves with the captcha.bot on discord, we we will continue to use the one standard invite link and list the available languages as is done on the [Internationalization and Localization (i18n)](https://wiki.alephium.org/misc/Internationalization-and-Localization) page.
