### ISSUE TITLE
Replace Docusaurus with Mkdocs

### ISSUE THREAD

**Issue by MaudSimon** [alephium/docs#330]
Recommendation from @chainrocker: 

>  MkDocs-Material might be an alternative. It supports 60 languages and there's a way to run multiple languages simultaneously through a plugin. 
> 
> https://squidfunk.github.io/mkdocs-material
> 
> https://squidfunk.github.io/mkdocs-material/discussions/2346
> 
> https://github.com/ultrabug/mkdocs-static-i18n

@mvaivre @nop33 when we have the bandwidth to pick up this discussion.

**Comment by Chainrocker** [comment]
**Here is a demo of the Mkdocs version**

[Alephium Docs - Demo](https://chainrocker.github.io/mkdocs-material-alephium-docs-demo/site/)

**Comment by nop33** [comment]
Hello! Thanks for the demo!

> MkDocs-Material might be an alternative

What is the reason for suggesting an alternative? Is our current solution (https://docusaurus.io/) lacking something?

**Comment by Chainrocker** [comment]
The reason for the suggestion is that Docusaurus apparently struggles with multilingual support. That's why I proposed MkDocs-material as an alternative.

**Comment by nop33** [comment]
Thanks for the reply! Hm, I am curious to know what the struggle with [Docusaurus](https://docusaurus.io/docs/i18n/introduction) is and how MkDocs solves it!

**Comment by MaudSimon** [comment]
@nop33 we discussed the struggle just above in that same issue.

**Comment by MaudSimon** [comment]
@nop33 @Chainrocker  we discussed the issue here: https://github.com/alephium/docs/issues/209

**Comment by MaudSimon** [comment]
@Chainrocker Does MkDocs solves the limitation of Docusaurus layed out in #209 ? How so ?

**Comment by nop33** [comment]
Closing this issue since we are happy with the Docusaurus integration into our Crowdin project. Anyone who wants to help us translate the docs can do it here! https://translate.alephium.org/
