### ISSUE TITLE
Why use Docusaurus instead of Markdoc?

### ISSUE THREAD

**Issue by ferdinandhodl** [alephium/docs#34]
why [docusaurus](https://docusaurus.io/) and not [Markdoc](https://markdoc.io/)?

**Comment by polarker** [comment]
> why [docusaurus](https://docusaurus.io/) and not [Markdoc](https://markdoc.io/)?

We use [docusaurus](https://docusaurus.io/) as more projects using it, so I guess the toolchain is more mature. [Markdoc](https://markdoc.io/) looks cool as well.

**Comment by nop33** [comment]
What's wrong with docusaurus? Docusaurus is React-based, which is our main frontend framework (website, desktop wallet, explorer, mobile wallet, voting demo). We like to keep the stack simple, since the team is familiar with it :)

**Comment by Sakrecoer** [comment]
Thanks for your question and recommendation @ferdinandhodl :purple_heart: 
Closing this issue as we will continue to use Docusaurus for the foreseeable future.
