### ISSUE TITLE
Cannot switch back to French language in specific page

### ISSUE THREAD

**Issue by nop33** [alephium/docs#48]
I noticed this issue in the page _"A primer with the desktop wallet"_ (see video)

https://user-images.githubusercontent.com/1579899/175969142-bb0c06ad-c848-4a18-b861-d2eeeec385e2.mp4

**Comment by Sakrecoer** [comment]
~~I can't reproduce this on neither Firefox 101.0.1 nor Chromium 103.0.5060.53~~

That page is gone now. Maybe this should be closed?
