### ISSUE TITLE
Remove the dapps section

### ISSUE THREAD

**Issue by LeeAlephium** [alephium/docs#50]
> The entire dapps section can be removed since it's not ready for primetime; even the pages that appear done are definitely not compatible day-to-day with the evolution of things

**Comment by nop33** [comment]
Some pages could stay, we need to link to something from the "Build" card of our website. https://alephium.org/

**Comment by LeeAlephium** [comment]
Anything to do with dApps can't be documented until dApp functionality is ready for the public to use... The wiki is a public resource so it only makes sense to provide information which can actually be used by the public (this was not my original stance on the wiki but it's changed since my understanding of its goals weren't correct)

We should probably not provide a "Build" card unless we create a page describing how people can build on Alephium in a way other than using dApps

**Comment by Sakrecoer** [comment]
Fixed by https://github.com/alephium/wiki/pull/52 Not sure why this issue didn't auto-close. Closing manually
