### ISSUE TITLE
Feature request: internal search function

### ISSUE THREAD

**Issue by Sakrecoer** [alephium/docs#67]
To help users orient themselves in the wiki, we'd be happy to see a search function being added to the docusaurus.

There seem to be several different ways to go about it, but all of them requires involvement from a developer. The releavant docusaursu documentation is available here: https://docusaurus.io/docs/search

Thanks :raised_hands:

**Comment by nop33** [comment]
I put it in my todo list, will check soon :)

**Comment by nop33** [comment]
@Sakrecoer would you like taking care of applying for the Algolia DocSearch program as described in the link you sent me?

**Comment by Sakrecoer** [comment]
@nop33 sure! :) I can try!

**Comment by Sakrecoer** [comment]
Just an update to document that I've filled out the application form for the Algolia DocSearch program today: https://docsearch.algolia.com/apply

We qualify so it should be fine. For reference, i used the `community` email address.

**Comment by Sakrecoer** [comment]
Have recieved the relevant snippets. Will look into it this week

**Comment by Sakrecoer** [comment]
There is an apiKey in there so i didn't want to paste the code they sent me here in the issue, although i'm pretty sure the key only works with our URL (`wiki.alephium.org`) and looking at the location the code has to be, i doubt it is secret. Better safe than sorry though, so i sent it privately to @LeeAlephium for now. :)
